FROM docker.io/php:8.5-fpm-alpine3.22@sha256:fb8a614d88503b12b8801603b5df220f7c09553c91708d1423e503e4656e6300

RUN  set -ex; \
  \
  apk update; \
  apk add libpq-dev libxml2-dev nodejs npm icu-dev git; \
  apk add --no-cache ${PHPIZE_DEPS} imagemagick imagemagick-dev; \
  \
  docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd; \
  docker-php-ext-install mysqli pdo pdo_mysql xml; \
  docker-php-ext-configure intl && docker-php-ext-install intl; \
  \
  apk add --no-cache freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev && \
  docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg && \
  docker-php-ext-install -j$(nproc) gd && \
  apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev && \
  \
  apk add ghostscript

RUN pecl install -o -f imagick\
    &&  docker-php-ext-enable imagick

RUN apk del --no-cache ${PHPIZE_DEPS}

RUN  apk add --no-cache libzip-dev && docker-php-ext-configure zip  && docker-php-ext-install zip
COPY ./php /usr/local/etc/php
CMD ["php-fpm"]